// config.js
const fs = require("fs");
require("dotenv").config();

const config = {
  SESSION_ID: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZUw5S2RxZ2UvazBJOGRDelNuRDcyaHBlb0Q2N2Z0THF6a3NZOU16T1cxcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiM05rbHJaUWtUbVMxbDFWNTZBRk9SNWd5MW56ZkNHYllHR1o3dW82WWltbz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJjRmQxZ2dRWHFGNWJlWXJ6WGpqa2FlZ0F5ZDVzY1hYZEFiZVRqR3hrUm5FPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI5T2dZazRUR0VTMFB4MERVZFcxNWhuZ2praXBvdURMbVFuTmlwTUU0T1NZPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjZOYWcySWplTkRPWFdDRkpHNmZ0RjQ5KzRlKzkyT3JIQ0xMNFFZeXhta2c9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik9IVGNFUzhUMWllOTUxN1l0TDFVMXo0cU1WNzdXVjdYdHJHbVRlUFdvelE9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid001OW1JSnY2TVplOE9CWWsreElJZ0l3bXJrOFY5VjJydWdReEdCMjlHaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUURsa3orTVZ2eEVHOU9peXlsK2ROT2l0SFZNQ3VYYjlVVHhtdGljdVJ5bz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNLNnNTc1NBN2hMNmtuLy9yTjF4VStYOC9CY25nUEhFK2VnaWdPTkNFeFE2YzB3LzAwZitOR0lVV2tSOTFoT3NOSDNueWlFbFQ5aUY0RlpjWmFDTERBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjQ0LCJhZHZTZWNyZXRLZXkiOiJXUkpMVCswV0J1eS9CZ0JPUzQ3LzEzajNLT3I5ZXorZVIzeWFXbFJOTENjPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI2Mzc4OTA2ODc3NkBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI2RjhENzU0Mzg0M0IyMkZFODYyMzIwMzYzOTU5QTkyOSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzIxNDcxNTU3fV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJrOG9uZGR3TVREQ1hXVFF4dEFRaFVRIiwicGhvbmVJZCI6Ijg2OGY0MDBiLTU0OGUtNDc2OS05ZmYwLTk5MzEwOTBkOTAxNiIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI0OElWRmRSQ0xQZlA5OFZtOU9jak1IdG8rMHM9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaDRUYmd1QWMzeCtnWjd6Z2tiZGxXQ0VUVktzPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IllTVlpWVE5BIiwibWUiOnsiaWQiOiIyNjM3ODkwNjg3NzY6MUBzLndoYXRzYXBwLm5ldCIsImxpZCI6IjE0MTAwNDMxMzIxOTA5NjoxQGxpZCIsIm5hbWUiOiJQcmFpc2UgQ2hvcmVvZ3JhcGh5In0sImFjY291bnQiOnsiZGV0YWlscyI6IkNLT1JrekFRc0tUdXRBWVlBU0FBS0FBPSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJNdWc1Z3VWSVhJUVBnczhXVmtNNjltY2gvcUg3blRIc0J1ZEs4cG1pM1dRPSIsImFjY291bnRTaWduYXR1cmUiOiJZVEovWEVVcUZTT3JhV3FlTEVQcGt6eUwyQWtJR0hZZkFzSGYrQ00wN3dUY2ZtMmJVdXkzZ1RlK1hHOUsrbmlJMS9YUnpDc2I5ek0wN0RFTDRGbnlDQT09IiwiZGV2aWNlU2lnbmF0dXJlIjoicG1Ya0RjZVZtUFpiZGh1VHp1OEprdzJXdGF5QnBOU25BbUN0WXNMd1hXQXpNanA3Qyt2c3dSMG5PRUdYY0Y2VWFBa2xwYndqeGZYL05sV09zTjFaQXc9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNjM3ODkwNjg3NzY6MUBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJUTG9PWUxsU0Z5RUQ0TFBGbFpET3ZabklmNmgrNTB4N0FiblN2S1pvdDFrIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzIxNDcxNTUwLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQU5wSiJ9",
  AUTO_STATUS_SEEN: process.env.AUTO_STATUS_SEEN !== undefined ? process.env.AUTO_STATUS_SEEN === 'true' : true, 
  AUTO_DL: process.env.AUTO_DL !== undefined ? process.env.AUTO_DL === 'true' : false,
  AUTO_READ: process.env.AUTO_READ !== undefined ? process.env.AUTO_READ === 'true' : false,
  AUTO_TYPING: process.env.AUTO_TYPING !== undefined ? process.env.AUTO_TYPING === 'true' : false,
  AUTO_RECORDING: process.env.AUTO_RECORDING !== undefined ? process.env.AUTO_RECORDING === 'true' : false,
  ALWAYS_ONLINE: process.env.ALWAYS_ONLINE !== undefined ? process.env.ALWAYS_ONLINE === 'true' : false,
  AUTO_REACT: process.env.AUTO_REACT !== undefined ? process.env.AUTO_REACT === 'true' : false,
   /*auto block only for 212 */
  AUTO_BLOCK: process.env.AUTO_BLOCK !== undefined ? process.env.AUTO_BLOCK === 'true' : true,
  
  
  REJECT_CALL: process.env.REJECT_CALL !== undefined ? process.env.REJECT_CALL === 'true' : false, 
  NOT_ALLOW: process.env.NOT_ALLOW !== undefined ? process.env.NOT_ALLOW === 'true' : true,
  MODE: process.env.MODE || "public",
  OWNER_NAME: process.env.OWNER_NAME || "✪⏤͟͞★⃝ꪶ‎𝞢𝙏𝞖𝞘-𝞛𝘿𖥘✪͜͡➺",
  OWNER_NUMBER: process.env.OWNER_NUMBER || "263789068776",
  GEMINI_KEY: process.env.GEMINI_KEY || "",
  WELCOME: process.env.WELCOME !== undefined ? process.env.WELCOME === 'true' : false, 
};


module.exports = config;
